/*
 * SPI_PROTOTYPES.h
 *
 * Created: 11/27/2023 10:01:56 PM
 *  Author: khaled waleed
 */ 


#ifndef SPI_PROTOTYPES_H_
#define SPI_PROTOTYPES_H_

#include "SPI_CONFIG.h"

/*
 -> STATES IF THE SPI WILL WORK AS A MASTER OR AS A SLAVE .. DIO PINS DIRECTION ( SS , MOSI , MISO , CLOCK SCK ) 
 -> STATES THE INTERRUPT MODE
*/

void SPI_INT ( void );


/*
 -> STATES THE PRE_SCALLER VALUE
*/
void SPI_MASTER_PRE_SCALLER (void);


/*
 MAKES THE SPI STARTS THE TRANSMISION .. BY WRITTING 0 ON THE PIN CONNECTED TO IT ( THE ONE WORKS AS SS ) 
*/

void SPI_MASTER_TRANS_START (void ); 

/*
 MAKES THE SPI STOPS THE TRANSMISION .. BY WRITTING 1 ON THE PIN CONNECTED TO IT ( THE ONE WORKS AS SS )
*/

void SPI_MASTER_TRANS_STOP (void );

/*
 -> RESPONSIBLE FOR SENDING AND READ DATA BETWEEN THE MASTER AND THE SLAVE 
 
 -> SEND AND READ AT THE SAME TIME  
*/

uint8 SPI_SNED_RECEIVE (uint8 DATA ) ;









#endif /* SPI_PROTOTYPES_H_ */