/*
 * ADC_IMPLEMENTATION.c
 *
 * Created: 11/27/2023 8:54:43 PM
 *  Author: khaled waleed
 */ 


#include "ADC_PROTOTYPES.h"
#include "DIO_PROTOTYPES.h"

void ADC_INIT (ADC_PRESCALER_VALUE PRESCALER_VALUE)
{
	
	/*
	ENABLING ADC
	SELECTING PRESCALER_VALUE
	*/
	
	ADCSRA |= (1<<7)|PRESCALER_VALUE;
	
	ADMUX = 0x00;
	
	// ADC PORT DEFINED AS INPUT
	
	DIO_SET_PORT_DIREC(DIO_PORTF,DIO_PORT_INPUT);
	

	}




uint16 ADC_READ_VALUE (ADC_CHANNEL_ID CHANNEL,ADC_ADJUSTMENT_CONRTOL ADJUST ,ADC_VOLTAGE VOLTAGE)
{
	
	
	ADMUX |= (CHANNEL & 0x1F) | (ADJUST & 0x20)| (VOLTAGE & 0xC0);
	
	// ADC START CONVERSION
	
	SET_BIT(ADCSRA,6);
	
	// CHECK ADC INTERRUPT FLAG
	
	while(GET_BIT(ADCSRA,6) == 1);
	
	//SET_BIT(ADCSRA,4);
	
	return ADC_ADJUST;
}