/*
 * ADC_PROTOTYPES.h
 *
 * Created: 11/27/2023 8:55:11 PM
 *  Author: khaled waleed
 */ 


#ifndef ADC_PROTOTYPES_H_
#define ADC_PROTOTYPES_H_


#include "ADC_CONFIG.h"

/*
* ENEBLE THE ADC
* SELECTION OF VOLTAGE REFRENCE SOURCE
* SELECTION OF ADJUST TYPE
* SELECTION OF CHANNEL ( WHICH PIN FROM THE 8 PINS OF THE ADC )
* TYPE OF TRIGGERNING  ( AUTO , MANUAL )
* SELECTION OF PRE-SCALLER
*/

void ADC_INIT (ADC_PRESCALER_VALUE PRESCALER_VALUE);

/*
* READING AND RETURING THE READING
* WE WILL STATE THE ADJUST TYPE ( RIGHT OR LEFT ADJUST )
*/

uint16 ADC_READ_VALUE (ADC_CHANNEL_ID CHANNEL,ADC_ADJUSTMENT_CONRTOL ADJUST ,ADC_VOLTAGE VOLTAGE);




#endif /* ADC_PROTOTYPES_H_ */