/*
 * TIMER_0_PRORTOTYPES.h
 *
 * Created: 11/27/2023 9:13:29 PM
 *  Author: khaled waleed
 */ 


#ifndef TIMER_0_PRORTOTYPES_H_
#define TIMER_0_PRORTOTYPES_H_


#include "TIMER_0_CONFIG.h"


/*
 STATES THE MODE OF OPERATION & INTERRUPT 
*/

void TIMER_0_INT (void);  

/*
 TO START THE TIMER .. AT WHICH U STATE THE PRE-SCALLER VALUE .. THE TIMER WORKS AUTOMATICALLY WHEN RECIVES A SIGNAL  
*/

void TIMER_0_START (void);

void TIMER_0_STOP (void);   

/*
 THE FUNCTION AT WHICH WE STATE THE TIME NEEDED 
 
 IN THIS FUNCTION WE CALCULATE THE FOLLWING :
 
 1) TIME FOR EACH TICK 
 2) TOTAL NUMBER OF TICKS FOR THE GIVEN TIME 
 3) STARTING TICK VALUE FOR THE GIVEN TIME ( TO REACH THE FLAG TICK AT THE GIVEN TIME ) 
 4) NUMBER OF OVER-FLOWS NEEDED
*/ 


void TIMER_0_SET_TIME (uint32 WANTED_TIME_MSEC); 

/*
 WHERE THE CALCULATIONS ARE MADE .. BASES ON EACH MODE
*/

void TIMER_0_SET_DUTY_CYCLE (uint8 DUTY_CYCLE); 

/*
 TO START THE DUTY CYCLE .. AT WHICH U STATE THE PRE-SCALLER VALUE .. WORKS AUTOMATICALLY WHEN RECIVES A SIGNAL  
*/

void TIMER_0_DUTY_CYCLE_START (void);


#endif /* TIMER_0_PRORTOTYPES_H_ */